# Generated by Django 3.2.5 on 2021-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
