# Generated by Django 3.2.5 on 2021-07-25 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_articles_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان نوشتار'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('p', 'منتشرشده'), ('d', 'پیش نویس')], max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
    ]
