# Generated by Django 3.2.5 on 2021-08-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'ذسته بندی ها'},
        ),
    ]
