# Generated by Django 3.2.5 on 2021-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('p', 'منتشرشده'), ('d', 'پیش نویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=10, verbose_name='وضعیت'),
        ),
    ]
