# Generated by Django 3.2.5 on 2021-09-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210908_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'نشانی آی پی', 'verbose_name_plural': 'نشانی های آی پی'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='hits',
        ),
    ]
