# Generated by Django 3.2.5 on 2021-09-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210909_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='articles.ArticleHit', to='articles.IPAddress', verbose_name='بازدید ها'),
        ),
    ]
