# Generated by Django 3.2.5 on 2021-09-12 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('articles', '0014_articlerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', through='articles.ArticleRating', to=settings.STAR_RATINGS_RATING_MODEL, verbose_name='امتیازات'),
        ),
    ]
