# Generated by Django 3.2.5 on 2021-09-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_articles_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='ArticleRating',
        ),
    ]
