# Generated by Django 3.2.5 on 2021-09-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0005_rating_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
